### ISSUE TITLE
error about zmumps

### ISSUE THREAD

**Issue by GengSS** [gudasergey/fdmnes#5]
Hi,

I wonder that is there any known issue about the zmumps library.
I frequently encounter an error like this:
```

 ** ERROR RETURN ** FROM ZMUMPS INFO(1)=-13
 ** INFO(2)=1157193372
```

This error seems to take place randomly,  at any stages of fdmnes running. Some of the simulations are terminated normally, but half of them is killed with this error.

I did not compile fdmnes by myself, and I just downloaded this parallel_fdmnes from this site and executed the binary with

`mpirun_fdmnes -np 8`

Would you please kindly send me some advices on how to solving this error? Thank you very much in advance. 

Best
Geng

**Comment by gudasergey** [comment]
Error -13 in MUMPS means, that there is not enough memory.

2018-06-05 0:17 GMT+03:00 GengSS <notifications@github.com>:

**Comment by GengSS** [comment]
Dear Sergey,

Thanks for your prompt reply.
From my understanding, the second number after INFO(2) is the required memory size.
1157193372 bytes = 1.15 GB, but I have 32 GB available for this calculation.

So I wonder how much virtual memory required for FDMNES? how to estimate the memory size?
Firstly, after some tests, I find that most of the time, this error jump up just after the SCF is converged. 

This is my input file
 ```
Filout
  Pt_L3

 Range
-20.0 2. -10.  0.1  2. 0.2  5. 0.5 20. 1. 50. 2. 80.

 Radius
  6.0

! Green
 !Relativism
 Spinorbite
 SCF
 Excited


 !Crystal
 Cif_file
 h4_ptsta_opt.cif

Edge
L3

! keywords for the convolution

 Convolution
 
 Estart
 -40.

End
```

This are headers of the standard output, so we know that the calculation has only 35 atoms.

```
 FDMNES II program, Revision 23th of May 2018
   Date = 04 06 2018
   Time = 13 h 55 mn 49 s

   range
   radius
   relativis
   spinorbit
   scf
   excited
   cif_file
   edge

 Filout: Pt_L3
 Threshold: Platinum L3 edge

 Parallel calculation with MUMPS Solver
  with  8 processors including  8 for the energy loop and  1 for MUMPS

 Number of calculated non equivalent absorbing atom =  1

 E_edge     = 11564.00 eV
 Cluster radius = 6.00 A, nb. of atom =  35

```

So, how many virtual memory should I use for this calculation?

Thank you very much in advance.

Geng

**Comment by gudasergey** [comment]
MUMPS works with sparse matrix format, so it has to allocate memory for
every row/column/part of a matrix separately. The estimation of memory size
is very hard task, because the sparse matrix form is used. We can't predict
how many zeros will be in the result of LU decomposition. Before your error
it allocated a lot of memory fragments. The last fragment had
size 1157193372 bytes = 1.15 GB and the total size of the matrix overfill
your memory 32 Gb. More over - you calculate 8 energies at one time. So for
one matrix you provide only 32/8 = 4 Gb. It is too small amount of memory.
From my experiments, for cluster radius 7 you need 60Gb (for each mpi
process!), for cluster radius 5 - 5Gb is enough.

2018-06-05 18:32 GMT+03:00 GengSS <notifications@github.com>:
